name: data-science-handbook
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - timeit
  - pandas  
  - netCDF4 
  - xarray 
  - dask
  - numpy  
  - datetime 
  - scipy
  - math
  - random
  - ipywidgets 
  - traitlets 
  - mpl_toolkits

  - pip:
    - yodapy
    - utm
    - pygeotools
