name: data-science-handbook
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - pandas  
  - netCDF4 
  - xarray 
  - dask
  - gdal
  - numpy  
  - scipy
  - ipywidgets 
  - traitlets 

  - pip:
    - yodapy
    - utm
    - pygeotools
